apiVersion: networking.k8s.io/v1  # Specifies the API version for the Ingress resource.
kind: Ingress  # Defines this resource as an Ingress, which manages external access to services.
metadata:
  name: ingress-no-auth  # The name of the Ingress resource.
spec:
  rules:  # Defines routing rules for HTTP traffic.
  - host: test.com  # Specifies that this Ingress applies to requests made to "test.com".
    http:
      paths:
      - path: /first  # Routes requests with the path "/first" to the specified backend service.
        pathType: Prefix  # Matches any request with a URL path that starts with "/first".
        backend:
          service:
            name: bark/svc  # The name of the backend service that will handle the traffic.
            port:
              number: 80  # The port on which the backend service is running.

      - path: /second  # Routes requests with the path "/second" to the specified backend service.
        pathType: Prefix  # Matches any request with a URL path that starts with "/second".
        backend:
          service:
            name: meow/svc  # The name of the backend service that will handle the traffic.
            port:
              number: 80  # The port on which the backend service is running.